using System;

namespace DataAccess
{
    public enum DataProviderAction
    {
        Insert, Update, Delete
    }
    public enum Table
    {
        Account,
        Cooling_Request,
        Customer,
        Customer_Complaint,
        Customer_Contract,
        Information,
        Item,
        Monitoring_Seed_Quantity,
        Pallet,
        Report_Customer_Complaints,
        Report_On_Board,
        Repository,
        Role,
        RoleAccount,
        Sales_Report,
        Shipment,
        Shipment_Request,
        Supplier,
        Supplier_Contract,
    }
    public enum TableAccount
    {
        ID,
        AccountName,
        Password,
        FirstName,
        LastName,
        IdentifyID,
        Email,
        Phone,
        Mobile,
        InformationID,
        OrderID,
    }
    public enum TableCooling_Request
    {
        ID,
        Request_Date,
        ItemID,
        CustomerID,
        Requester,
        Delivery_Date,
        InformationID,
        OrderID,
    }
    public enum TableCustomer
    {
        ID,
        CustomerCode,
        CustomerName,
        Email,
        Phone,
        Mobile,
        InformationID,
        OrderID,
    }
    public enum TableCustomer_Complaint
    {
        ID,
        CustomerID,
        Grower_Claim,
        ItemID,
        SupplierID,
        Lot,
        Certificate,
        Import_Quantity,
        Delivery_Quantity,
        Selling_Date,
        ContID,
        Dmg_QTY_Before,
        Dmg_QTY_After,
        Checked_Date,
        Grower_Before,
        Grower_After,
        Conclusion_Before,
        Conclusion_After,
        Technical,
        Solution,
        Status,
        Claiming_Supplier,
        Note,
    }
    public enum TableCustomer_Contract
    {
        ID,
        Customer_Contract,
        Effective_Date,
        In_Charge,
        CustomerID,
        ItemID,
        Required_Supplier,
        Order_QTY_Bulbs,
        Price_VND,
        Seeding_Date_Lunar,
        Seeding_Date_Gregorian,
        Estimated_Arrival_Date,
        Note,
        ContID,
        Date_Arrived,
        Deposit,
        Date_1,
        Delivery_1,
        Date_2,
        Delivery_2,
        Date_3,
        Delivery_3,
        Date_4,
        Delivery_4,
        Date_5,
        Delivery_5,
        InformationID,
        OrderID,
    }
    public enum TableInformation
    {
        ID,
        NameInfor,
        DateCreated,
        CreatedBy,
        DateModified,
        ModifiedBy,
    }
    public enum TableItem
    {
        ID,
        ItemID,
        ItemName,
        Type,
        Size,
        ItemsPerPack,
        Crop,
        Note,
        Information,
        OrderID,
    }
    public enum TableMonitoring_Seed_Quantity
    {
        ID,
        Date_Added,
        ContID,
        ItemID,
        SupplierID,
        Lot,
        Certificate,
        Status,
        CustomerID,
        Export_Quantity,
        Export_Date,
        Damaged_Quantity,
        Customer_Feedback,
        Damaged_Status,
        Checked_Date,
        Note,
        Process_Status_Customer,
        Process_Status_Supplier,
        InformationID,
        OrderID,
    }
    public enum TablePallet
    {
        ID,
        Pallet,
        Tray_Number,
        ReposityID,
        ContID,
        Empty_Pallet,
    }
    public enum TableReport_Customer_Complaints
    {
        ID,
        Technical_staff,
        Customer_A_Quantity,
        Customer_A_Times,
        Customer_B_Quantity,
        Customer_B_Times,
        Customer_C_Quantity,
        Customer_C_Times,
        Customer_D_Quantity,
        Customer_D_Times,
        Result,
        InformationID,
        OrderID,
    }
    public enum TableReport_On_Board
    {
        ID,
        ItemID,
        SupplierID,
        Price_EUR,
        CustomerID,
        Order_Quantity,
        Unit_Price,
        Delivery_Time,
        Pay,
        InformationID,
        OrderID,
    }
    public enum TableRepository
    {
        ID,
        Repo_Name,
        Location,
        PalletID,
        ItemID,
        ContID,
        CustomerID,
        InformationID,
        OrderID,
    }
    public enum TableRole
    {
        ID,
        RoleName,
        Functions,
        InformationID,
        OrderID,
    }
    public enum TableRoleAccount
    {
        RoleID,
        AccountID,
        Active,
    }
    public enum TableSales_Report
    {
        ID,
        Year,
        Month,
        Export_Date,
        Date_Arrived,
        Check_Date,
        Export_Number,
        Bill_Number,
        CustomerID,
        ItemID,
        SupplierID,
        Certificate,
        Tuber_Number,
        Tray_Number,
        Price_VND,
        Status,
        Note,
        InformationID,
        OrderID,
    }
    public enum TableShipment
    {
        ID,
        Year,
        Month,
        ContID,
        ItemID,
        Purchase_Quantity_Bulbs,
        Price_EUR,
        Lot,
        Certificate,
        Quality_Control_Assessment,
        Note,
        InformationID,
        OrderID,
    }
    public enum TableShipment_Request
    {
        ID,
        CustomerID,
        ItemID,
        Reason,
        InformationID,
        OrderID,
    }
    public enum TableSupplier
    {
        ID,
        SupplierCode,
        SupplierName,
        Nation,
        InformationID,
        OrderID,
    }
    public enum TableSupplier_Contract
    {
        ID,
        Supplier_Contract_Name,
        Ordered_Date,
        SupplierID,
        ItemID,
        Purchase_Quantity_Bulbs,
        Price_EUR,
        Shipped_Quantity_Bulbs,
        Note,
        Comment,
        Schedule,
        ETD,
        ETA,
        Loading_Date,
        ETD_CMA_SCHEDULE,
        ETA_CMA_SCHEDULE,
        ETD_ONE_SCHEDULE,
        ETA_ONE_SCHEDULE,
        InformationID,
        OrderID,
    }

}
